TI_HW_03
lait1103/NFA pull request #1
Opened 2022-09-24 22:32 UTC by lait1103

2022-10-01 21:01 UTC, katyacyfra requested changes
Что выводит конвертер? Явно не тот формат, который прошу в задании. Поправьте, пожалуйста

2022-10-01 21:01 UTC, katyacyfra commented on src/test/kotlin/Tests.kt
> +        // Example from the task. I checked that it is done correctly (compared with notes from the class)
:sob: почему не сравнить нормально с тем, что должно получиться?

2022-10-01 21:03 UTC, katyacyfra requested changes

2022-10-01 21:03 UTC, katyacyfra commented on src/main/kotlin/NFA2DFA.kt
> +fun getInput(`in`: InputStream = System.`in`): Input {
У Вас есть требование, чтобы после всех переходов в файле был перевод строки, а иначе падает. Надо это указать где-либо

2022-10-06 22:23 UTC, lait1103 commented on src/test/kotlin/Tests.kt
> +        // Example from the task. I checked that it is done correctly (compared with notes from the class)
Поправил

2022-10-06 22:23 UTC, lait1103 commented on src/main/kotlin/NFA2DFA.kt
> +fun getInput(`in`: InputStream = System.`in`): Input {
Ага, добавил

2022-10-06 22:24 UTC, lait1103 commented
Тепербь формат правильный (раньше какая - то фигня была с количеством состояний / размером алфавита )

2022-10-14 16:54 UTC, katyacyfra approved these changes
Зачтено

2022-10-15 10:56 UTC, merged